version: '3'

services:

    server:
      build: ./server
      expose:
        - ${SERVER_PORT}
      environment:
        API_HOST: ${API_HOST}
        SERVER_PORT: ${SERVER_PORT}
      ports:
        - ${SERVER_PORT}:${SERVER_PORT}
      volumes:
        - ./server/src:/usr/src/app/server
      command: npm run dev

    client:
      build: ./client
      expose:
        - ${REACT_APP_PORT}
      environment:
        - REACT_APP_PORT=${REACT_APP_PORT}
      ports:
        - ${REACT_APP_PORT}:${REACT_APP_PORT}
      volumes:
        - ./client/src:/usr/src/app/src
        - ./client/public:/usr/src/app/public
      links:
        - server
      command: npm start
